# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AntiCRISPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('accession', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismAntiCRISPRPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_start', models.PositiveIntegerField(default=0)),
                ('genomic_end', models.PositiveIntegerField(default=0)),
                ('antiCRISPR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.AntiCRISPR')),
                ('organism', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='OrganismSpacerRepeatPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('genomic_start', models.PositiveIntegerField(default=0)),
                ('genomic_end', models.PositiveIntegerField(default=0)),
                ('organism', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='Phage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhageAntiCRISPRPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_start', models.PositiveIntegerField(default=0)),
                ('genomic_end', models.PositiveIntegerField(default=0)),
                ('antiCRISPR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.AntiCRISPR')),
                ('phage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Phage')),
            ],
        ),
        migrations.CreateModel(
            name='PhageSpacerPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genomic_start', models.PositiveIntegerField(default=0)),
                ('genomic_end', models.PositiveIntegerField(default=0)),
                ('phage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Phage')),
            ],
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Spacer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(blank=True, default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='SpacerRepeatPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Repeat')),
                ('spacer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Spacer')),
            ],
        ),
        migrations.AddField(
            model_name='phagespacerpair',
            name='spacer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.Spacer'),
        ),
        migrations.AddField(
            model_name='organismspacerrepeatpair',
            name='spacerrepeatpair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.SpacerRepeatPair'),
        ),
    ]
